module.exports = {
  RECEIVE_ALL_NOTEBOOKS: "RECEIVE_NOTEBOOKS",
  RECEIVE_NOTEBOOK: "RECEIVE_NOTEBOOK",
  DELETE_NOTEBOOK: "DELETE_NOTEBOOK",
  ERROR: "ERROR",
  RECEIVE_NOTEBOOK_NOTES: "RECEIVE_NOTEBOOK_NOTES"
};
